# Generated by Django 5.0.7 on 2024-08-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="rating",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1 Star"),
                    (2, "2 Star"),
                    (3, "3 Star"),
                    (4, "4 Star"),
                    (5, "5 Star"),
                ],
                default=5,
            ),
        ),
    ]
