# Generated by Django 5.0.7 on 2024-08-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_comment_created_at_category_recipe_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("cake", "Cake"), ("flavor", "Flavor")],
                max_length=50,
                null=True,
            ),
        ),
    ]
