# Generated by Django 5.0.7 on 2024-08-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_category_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
